POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###
GET http://localhost:3333/videos

###
PUT http://localhost:3333/videos/91fe5cc4-7bc3-4225-a1d8-4855bf4985ab
Content-Type: application/json

{
    "title": "Video 04",
    "description": "Esse é o quarto vídeo",
    "duration": 180
}

###
DELETE http://localhost:3333/videos/91fe5cc4-7bc3-4225-a1d8-4855bf4985ab